import re


def on_page_markdown(markdown, page, *, config, files, **kwargs):
    """Add data-search-exclude to raw HTML elements in markdown source.

    This targets only HTML tags explicitly written in .md files, not HTML
    generated by the markdown parser (e.g. <p>, <h1>, <code>). The search
    plugin indexes content at on_page_context, after this hook runs.
    """

    def inject_attribute(match):
        tag = match.group(0)
        if "data-search-exclude" in tag:
            return tag
        return re.sub(r"(\s*/?>)$", r" data-search-exclude\1", tag)

    return re.sub(r"<(?![\!/])[a-zA-Z][^>]*>", inject_attribute, markdown)


def on_page_content(html, page, *, config, files, **kwargs):
    """Add data-search-exclude to data-termynal elements in rendered HTML.

    Snippet files are resolved after on_page_markdown, so their HTML is only
    available here. Targets data-termynal elements specifically.
    """
    if "data-termynal" not in html:
        return html

    def inject_attribute(match):
        tag = match.group(0)
        if "data-search-exclude" in tag:
            return tag
        return re.sub(r"(\s*/?>)$", r" data-search-exclude\1", tag)

    return re.sub(r"<[a-zA-Z][^>]*data-termynal[^>]*>", inject_attribute, html)
